server:
  port: 8011
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: "https://localhost:8010/eureka" #注册中心地址
#    register-with-eureka: false #是否将自己注册到注册中心，默认为true，单节点建议关闭
#    fetch-registry: false #是否从注册中心获取服务器注册信息 默认为true，单节点建议关闭
  instance:
    instance-id: eureka-server-00
    ip-address: true
    hostname: localhost #主机名，不配置的时候将根据操作系统的主机名来获取