server:
  port: 8020
spring:
  application:
    name: eurekaClient
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8010/eureka,http://127.0.0.1:8011/eureka,http://127.0.0.1:8012/eureka
  instance:
    instance-id: eurekaClient1
    ip-address: true